config/routes.rb
Rails.application.routes.draw do
  resources :types do
    resources :businesses
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :type
  validates :name, :hours, :website, :phone_number, :address, :presence => true
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :businesses
  validates :category, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    @businesses = Business.all
    render :types
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.all
    render :index
  end

  def show
    @type = Type.find(params[:id])
    render :show
  end

  def new
    @type = Type.new
    render :new
  end

  def create
    @type = Type.new(type_params)
    if @type.save
      redirect_to types_path
    else
      render :new
    end
end

  def edit
    @type = Type.find(params[:id])
    render :edit
  end

  def update
    @type= Type.find(params[:id])
    if @type.update(type_params)
      redirect_to types_path
    else
      render :edit
    end
  end

  def destroy
    @type = Type.find(params[:id])
    @type.destroy
    redirect_to types_path
  end
end

private
  def type_params
    params.require(:type).permit(:category)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix the following errors</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikiPages</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/types/_form.html.erb
<%= render "layouts/errors", :object => @type %>

<%= form_for @type do |f| %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.submit %>
<% end %>

app/views/types/edit.html.erb
<h1>Edit Type</h1>

<%= render "form" %>

app/views/types/index.html.erb
<h1>Types</h1>

<ul>
  <% @types.each do |type| %>
  <li> <%= link_to type.category, type_path(type) %> </li>
  <% end %>
</ul>

<hr>

<%= link_to "New Type", new_type_path %>

app/views/types/new.html.erb
<h1>New Type of Business</h1>

<%= render "form" %>

app/views/types/show.html.erb
<h1> <%= @type.category %></h1>

<p><%= link_to "Edit", edit_type_path(@type) %></p>
<p><%= link_to "Delete", type_path(@type),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>